### ISSUE TITLE
[BUG] autogl 0.1.1 is not compactible with torch-geometric 1.6.3

### ISSUE THREAD

**Issue by iwatobipen** [THUMNLab/AutoGL#10]
**Describe the bug**
When I run the graph_classification.py code, I got following error.
How can I fix the error? Any advice will be greatly appreciated.
Thanks

`
~/src/AutoGL/examples$ python graph_classification.py 

Traceback (most recent call last):
  File "graph_classification.py", line 19, in <module>
    cv_split=10, 
  File "/home/user/src/AutoGL/autogl/solver/classifier/graph_classifier.py", line 294, in fit
    self.feature_module.fit(dataset.train_split)
  File "/home/user/src/AutoGL/autogl/module/feature/base.py", line 116, in fit
    dataset = self._rebuild(dataset, _dataset)
  File "/home/user/src/AutoGL/autogl/module/feature/base.py", line 57, in _rebuild
    data, slices = dataset.collate(datalist)
  File "/home/user/miniconda3/envs/grapl/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 128, in collate
    dim=data.__cat_dim__(key, item))
RuntimeError: Sizes of tensors must match except in dimension 0. Got 1 and 2 in dimension 1 (The offending index is 5)

`

**Environment (please complete the following information):**
 - OS: [Ubuntu20.04]
 - python version: [Python 3.7.9]
 - autogl version: [0.1.1]

**Comment by Frozenmad** [comment]
Thanks for your bug information. We will come back to you later after investigation.

**Comment by Frozenmad** [comment]
I've test the graph classification example under python 3.6.10 and autogl 0.1.1 and cannot reproduce the bug. Can you provide more information about the package you have installed? [output of `pip list`]

**Comment by iwatobipen** [comment]
Thanks for your prompt reply. Here is my list.
Thanks

Package                           Version             Location
--------------------------------- ------------------- --------------------------------------------------------
alabaster                         0.7.12
alembic                           1.4.3
altair                            4.1.0
AmberLite                         16.0
AmberTools                        17.0
anaconda-client                   1.7.2
appdirs                           1.4.4
argh                              0.26.2
argon2-cffi                       20.1.0
ase                               3.20.1
asn1crypto                        1.4.0
astor                             0.8.1
async-generator                   1.10
atomicwrites                      1.4.0
attrs                             20.3.0
auto-graph-learning               0.1.1               /home/iwatobipen/src/AutoGL
Babel                             2.9.0
backcall                          0.2.0
base58                            2.0.1
bayesian-optimization             1.2.0
beautifulsoup4                    4.9.3
biopandas                         0.2.7
biopython                         1.78
bleach                            3.2.1
blinker                           1.4
blis                              0.4.1
boto                              2.49.0
boto3                             1.16.42
botocore                          1.19.42
brotlipy                          0.7.0
cached-property                   1.5.2
cachetools                        4.1.1
catalogue                         1.0.0
catboost                          0.24.3
certifi                           2020.12.5
cffi                              1.14.4
chardet                           4.0.0
chart-studio                      1.1.0
chocolate                         0.0.2
click                             7.1.2
cloudpickle                       1.6.0
clyent                            1.2.2
colorama                          0.4.4
colorlover                        0.3.0
conda                             4.9.2
conda-build                       3.20.5
conda-package-handling            1.7.2
configparser                      5.0.1
confuse                           1.4.0
cryptography                      3.3.1
cufflinks                         0.17.3
cycler                            0.10.0
cymem                             2.0.4
Cython                            0.29.21
cytoolz                           0.11.0
dask                              2020.12.0
databricks-cli                    0.9.1
dataclasses                       0.6
datefinder                        0.7.1
decorator                         4.4.2
deepdiff                          5.0.2
defusedxml                        0.6.0
dill                              0.3.3
distro                            1.5.0
docker                            4.4.0
docker-pycreds                    0.4.0
docopt                            0.6.2
docutils                          0.15.2
entrypoints                       0.3
fastjsonschema                    2.14.5
filelock                          3.0.12
Flask                             1.1.2
funcy                             1.15
future                            0.18.2
gensim                            3.8.0
gitdb                             4.0.5
GitPython                         3.1.11
glob2                             0.7
gorilla                           0.3.0
gunicorn                          20.0.4
h5py                              2.8.0
htmlmin                           0.1.12
hyperopt                          0.2.5
idna                              2.10
imagecodecs                       2020.5.30
ImageHash                         4.2.0
imageio                           2.9.0
imagesize                         1.2.0
importlib-metadata                2.0.0
importlib-resources               3.3.1
ipykernel                         5.3.4
ipython                           7.19.0
ipython-genutils                  0.2.0
ipywidgets                        7.5.1
isodate                           0.6.0
itsdangerous                      1.1.0
Jinja2                            2.11.2
jmespath                          0.10.0
joblib                            1.0.0
jsonpickle                        1.4.2
jsonschema                        3.0.2
jupyter                           1.0.0
jupyter-client                    6.1.7
jupyter-console                   6.2.0
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.7.0
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyterlab-pygments               0.1.2
kiwisolver                        1.3.0
kmodes                            0.10.2
libarchive-c                      2.9
lightgbm                          3.1.1
littleutils                       0.2.2
llvmlite                          0.34.0
lxml                              4.6.2
Mako                              1.1.3
MarkupSafe                        1.1.1
matplotlib                        3.3.2
missingno                         0.4.2
mistune                           0.8.4
mkl-fft                           1.2.0
mkl-random                        1.1.1
mkl-service                       2.3.0
mlxtend                           0.18.0
modeller                          0.1.1
more-itertools                    8.6.0
msgpack                           1.0.1
murmurhash                        1.0.5
nbclient                          0.5.1
nbconvert                         6.0.7
nbformat                          5.0.8
nest-asyncio                      1.4.3
NetLSD                            1.0.2
networkx                          2.5
nglview                           2.7.7
nltk                              3.5
notebook                          6.1.5
numba                             0.51.2
numexpr                           2.7.1
numpy                             1.19.2
ogb                               1.2.4
olefile                           0.46
openforcefields                   1.3.0
OpenMM                            7.5.0
ordered-set                       4.0.2
outdated                          0.2.0
packaging                         20.8
packmol-memgen                    1.0.5rc0
pandas                            1.1.5
pandas-profiling                  2.9.0
pandocfilters                     1.4.3
ParmEd                            3.2.0
parso                             0.8.1
pathtools                         0.1.2
patsy                             0.5.1
pdb4amber                         1.7.dev0
pexpect                           4.8.0
phik                              0.10.0
pickleshare                       0.7.5
pigeonXT-jupyter                  0.4.1
Pillow                            8.0.1
Pint                              0.16.1
pip                               20.3.3
pipreqs                           0.4.10
pkginfo                           1.6.1
plac                              1.1.0
plotly                            4.14.1
pluggy                            0.13.1
Pmw                               2.0.1
preshed                           3.0.2
progressbar2                      3.53.1
prometheus-client                 0.9.0
prompt-toolkit                    3.0.8
protobuf                          3.14.0
psutil                            5.7.3
ptyprocess                        0.6.0
py                                1.10.0
pyarrow                           2.0.0
pycairo                           1.19.1
pycaret                           2.1.2
pycosat                           0.6.3
pycparser                         2.20
pydantic                          1.7.3
pydeck                            0.5.0
Pygments                          2.7.3
pyLDAvis                          2.1.2
pymbar                            3.0.5
pymol                             2.5.0a0
pyMSMT                            19.0
pyod                              0.8.4
PyOpenGL                          3.1.1a1
pyOpenSSL                         20.0.1
pyparsing                         2.4.7
PyQt5                             5.12.3
PyQt5-sip                         4.19.18
PyQtChart                         5.12
PyQtWebEngine                     5.12.1
pyreadline                        2.1
pyrsistent                        0.17.3
PySocks                           1.7.1
pytest                            4.6.4
python-dateutil                   2.8.1
python-editor                     1.0.4
python-louvain                    0.15
python-utils                      2.4.0
pytraj                            2.0.5
pytz                              2020.4
PyWavelets                        1.1.1
PyYAML                            5.3.1
pyzmq                             20.0.0
qcelemental                       0.17.0
qtconsole                         4.7.7
QtPy                              1.9.0
querystring-parser                1.2.4
rdflib                            5.0.0
readline                          6.2.4.1
regex                             2020.11.13
reportlab                         3.5.51
requests                          2.25.1
retrying                          1.3.3
ruamel-yaml                       0.15.87
s3transfer                        0.3.3
sander                            16.0
scikit-build                      0.11.1
scikit-image                      0.17.2
scikit-learn                      0.23.2
scipy                             1.5.2
seaborn                           0.11.1
Send2Trash                        1.5.0
setuptools                        51.0.0.post20201207
shap                              0.36.0
simplejson                        3.17.2
six                               1.15.0
slicer                            0.0.7
smart-open                        1.8.0
smmap                             3.0.4
snowballstemmer                   2.0.0
soupsieve                         2.1
spacy                             2.3.5
Sphinx                            3.4.1
sphinx-rtd-theme                  0.5.0
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            1.0.3
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.4
SQLAlchemy                        1.3.21
sqlparse                          0.4.1
srsly                             1.0.5
statsmodels                       0.12.1
streamlit                         0.73.1
tabulate                          0.8.7
tangled-up-in-unicode             0.0.6
terminado                         0.9.1
testpath                          0.4.4
textblob                          0.15.3
thinc                             7.4.5
threadpoolctl                     2.1.0
tifffile                          2020.12.8
toml                              0.10.2
toolz                             0.11.1
torch                             1.7.0
torch-cluster                     1.5.8
torch-geometric                   1.6.3
torch-scatter                     2.0.5
torch-sparse                      0.6.8
torch-spline-conv                 1.2.0
torchaudio                        0.7.0a0+ac17b64
torchvision                       0.8.1
tornado                           6.1
tqdm                              4.54.1
traitlets                         5.0.5
typing-extensions                 3.7.4.3
tzlocal                           2.1
umap-learn                        0.4.6
urllib3                           1.25.11
validators                        0.18.2
visions                           0.5.0
wasabi                            0.8.0
watchdog                          1.0.2
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  0.57.0
Werkzeug                          1.0.1
wheel                             0.36.2
widgetsnbextension                3.5.1
wordcloud                         1.8.1
xgboost                           1.3.0
yarg                              0.1.9
yellowbrick                       1.2
zipp                              3.4.0

**Comment by Frozenmad** [comment]
Thanks for your info. I've done some tests and find that the `autogl=0.1.1` is not compactable with `torch-geometric>1.6.1`. We'll fix the bug in the future version of autogl to support up-to-date torch-geometric package.

For now, you can just lower your pytorch geometric package by:
```
pip install torch-goemtric==1.6.1
```

Thanks again for your info!

**Comment by iwatobipen** [comment]
I confirmed. The code worked with torch-geometric 1.6.1.
Thanks for your kind support and nice work.
