### ISSUE TITLE
[BUG] KeyError: 'NormalizeFeatures'

### ISSUE THREAD

**Issue by ScottHoang** [THUMNLab/AutoGL#106]
**Describe the bug**
Missing key in FEATURE_DICT line 764, in from_config from file 
"/home/scotthoang/anaconda3/envs/autogl/lib/python3.8/site-packages/autogl/solver/classifier/node_classifier.py",
**To Reproduce**
1. Go to 'examples'
2. Run "python gasso_test.py"

**Expected behavior**
To run normally without error.

**Screenshots**

Traceback (most recent call last):
```
  File "gasso_test.py", line 20, in <module>
    solver = AutoNodeClassifier.from_config(args.config)
  File "/home/scotthoang/anaconda3/envs/autogl/lib/python3.8/site-packages/autogl/solver/classifier/node_classifier.py", line 764, in from_config
    fe_list_ele.append(FEATURE_DICT[name](**feature_engineer))
KeyError: 'NormalizeFeatures'
```

**Environment (please complete the following information):**
 - OS: PopOS 21.10
 - python version: 3.8.5
 - autogl version: 0.2.0-pre

**Comment by CoreLeader** [comment]
For now, AutoGL 0.3.1 has been released, I suggest that you would better upgrade autogl to version `0.3.1` with `Pytorch-Geometric (PyG)` backend to utilize GASSO.

Best wishes.

**Comment by ScottHoang** [comment]
Thank you~ I did what you suggested and it works.
I have an additional question. is example/gasso_test.py a purely evaluating code? How do I train a new dataset following GASSO?

**Comment by general502570** [comment]
Actually, `example/gasso_test.py` already contains train & test procedures. You only need to change the dataset.
