### ISSUE TITLE
AttributeError: 'CoraDataset' object has no attribute 'data' [BUG]

### ISSUE THREAD

**Issue by jrcastropy** [THUMNLab/AutoGL#114]
**Describe the bug**
When getting the accuracy shared in the documentation using Cora Dataset I get this
`AttributeError: 'CoraDataset' object has no attribute 'data'`

**To Reproduce**
```
import torch
from autogl.datasets import build_dataset_from_name
from autogl.solver import AutoNodeClassifier
from autogl.module.train import Acc

cora_dataset = build_dataset_from_name('cora')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

solver = AutoNodeClassifier(
    feature_module='deepgl',
    graph_models=['gcn', 'gat'],
    hpo_module='anneal',
    ensemble_module='voting',
    device=device
)

solver.fit(cora_dataset, time_limit=3600)

predicted = solver.predict_proba()
print('Test accuracy: ', Acc.evaluate(predicted,
    cora_dataset.data.y[cora_dataset.data.test_mask].cpu().numpy()))
```

**Expected behavior**
it should print out the accuracy
`Test accuracy:  0.824`

**Screenshots**
![image](https://user-images.githubusercontent.com/71639738/184577439-f5a4cbb1-1466-47bd-b1a4-3d59e717714e.png)

**Environment (please complete the following information):**
 - OS: [Google Colab / Linux]
 - python version: Python 3.7.13
 - autogl version: 0.3.1

**Additional Info (Optional)**
Torch version is ('1.12.1', 'cu113')

I installed this
!pip install torch-scatter -f https://data.pyg.org/whl/torch-{tver}+{cuver}.html
!pip install torch-sparse -f https://data.pyg.org/whl/torch-{tver}+{cuver}.html
!pip install torch-geometric
!pip install dgl-cu113 dglgo -f https://data.dgl.ai/wheels/repo.html
!pip install netlsd
!pip install chocolate
!-m pip install git+https://github.com/fmfn/BayesianOptimization
!pip install autogl

**Comment by general502570** [comment]
Sorry for late response. Your solution is correct.
