### ISSUE TITLE
[FEATURE]The wechat code out of date.

### ISSUE THREAD

**Issue by SaraiQX** [THUMNLab/AutoGL#135]
As titled. Hopefully there could be more discussion groups via wechat or qq. Thanks for the great work.

**Comment by ZW-ZHANG** [comment]
Hi,
Thanks for your interests in autogl & the discussion! It seems that the wechat group has not been very active, so I would recommend openning issues or sending us emails at autogl@tsinghua.edu.cn for any discussion.
