### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shrutiOx** [THUMNLab/AutoGL#140]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - python version: [The output of cmd `python -V`]
 - autogl version: [The output of cmd `python -c 'import autogl; print(autogl.__version__)'`]
 - pip list: [the output of cmd `pip list`]

**Additional Info (Optional)**
Add any other context about the problem here. Such as the possible reason you think, or how to solve this bug if you are interested.

GraphClassification  not working.

""""""""""""""""""""""""""""""""""""""""
HPO Search Phase:

  0%|          | 0/10 [00:00<?, ?it/s]WARNING:root:Ignore passed dec since enc is a whole model
  0%|          | 0/10 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-142-58f7e1210478>](https://localhost:8080/#) in <cell line: 2>()
      1 # train
----> 2 autoClassifier.fit(dataset , evaluation_method=[Acc])
      3     #autoClassifier.get_leaderboard().show()
      4 
      5     #print("best single model:\n", autoClassifier.get_leaderboard().get_best_model(0))

4 frames
[/usr/local/lib/python3.10/dist-packages/autogl/datasets/utils/_general.py](https://localhost:8080/#) in graph_get_split(dataset, mask, is_loader, batch_size, num_workers, shuffle)
    369             raise RuntimeError("Unsupported backend")
    370         elif _backend.DependentBackend.is_dgl():
--> 371             from dgl.dataloading.pytorch import GraphDataLoader
    372             return GraphDataLoader(
    373                 sub_dataset,

ModuleNotFoundError: No module named 'dgl.dataloading.pytorch'

""""""""""""""""""""""""""""""""""""""""""""""""""""'''

**Comment by ZW-ZHANG** [comment]
Hi. It seems that this problem is related to DGL backend. Can you check that you have successfully installed DGL (e.g., by running its examples)?

**Comment by shrutiOx** [comment]
Hello, thank you very much for your reply. I am trying to install this but facing some problems.

Here are the libraries that I have installed to support AutoGL
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install  dgl -f https://data.dgl.ai/wheels/repo.html
!pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html
!pip install gensim==3.8
!pip install torch_scatter
!pip install torch_sparse
!pip install nni
!pip install torch_geometric
!pip install autogl

Then am getting this error:

import autogl


AttributeError                            Traceback (most recent call last)
[<ipython-input-20-8623c0a482c7>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import autogl

5 frames
[/usr/local/lib/python3.10/dist-packages/autogl/datasets/utils/_split_edges/split_edges.py](https://localhost:8080/#) in <module>
      3 import autogl
      4 
----> 5 if autogl.backend.DependentBackend.is_dgl():
      6     from ._dgl_compatible import split_edges_for_data
      7 elif autogl.backend.DependentBackend.is_pyg():

AttributeError: partially initialized module 'autogl' has no attribute 'backend' (most likely due to a circular import)



Can you please suggest what I need to do for successful install.

**Comment by shrutiOx** [comment]
Also to add that doing force install am getting this error:

      word2vec_inner.c
      gensim/models/word2vec_inner.c(216): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gensim
  Running setup.py clean for gensim
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492055 sha256=6ee6f5b8ef896c603b353c50cc246833783e94d2785a72381031c8dd654b9305
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\da\19\ca\9d8c44cd311a955509d7e13da3f0bea42400c469ef825b580b
Successfully built future
Failed to build gensim
ERROR: Could not build wheels for gensim, which is required to install pyproject.toml-based projects
