### ISSUE TITLE
Own Dataset

### ISSUE THREAD

**Issue by Kunjal1999** [THUMNLab/AutoGL#15]
How do I run the entire code on my own dataset? I have 44k graphs in networkx format.

**Comment by SwiftieH** [comment]
Hi,

You can simply transform your networkx format to pyg format and ready to go. 
Actually, pyg provides a function for this use simply by ``from torch_geometric.utils import from_networkx``. 
You can also refer to https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/utils/convert.html#from_networkx for more details.

**Comment by Frozenmad** [comment]
I'm closing this issue since it is inactive for a long time. Please feel free to re-open it or propose new issues if you have further questions!
