### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by THINK2TRY** [THUMNLab/AutoGL#5]
Hi, I just try to run examples/node_classification.py, but it reports an error `ModuleNotFoundError: No module named 'networkx.algorithms.efficiency_measures'`. I'm sure that I have installed `networkx2.3`. Could you tell me what should I do to successfully run the example?
![image](https://user-images.githubusercontent.com/48679723/102978064-e0fe8e80-453e-11eb-9fb7-0671454e80b9.png)

**Comment by Frozenmad** [comment]
Thanks for your bug report, we'll come back to you once we figure out what's wrong!

**Comment by Frozenmad** [comment]
@THINK2TRY 
It seems that the lowest version for `networkx` needed in `autogl` is 2.4. Please update your `networkx` to 2.4 by:
```cmd
pip install networkx>=2.4
```
We will update our version requirement of every package in the future versions!

**Comment by THINK2TRY** [comment]
Ok, it works. Thanks for your reply.
