### ISSUE TITLE
doc example: dataset.slices.update [BUG]

### ISSUE THREAD

**Issue by timruhkopf** [THUMNLab/AutoGL#59]
**Describe the bug**
following the doc example on [FE](http://mn.cs.tsinghua.edu.cn/autogl/documentation/docfile/tutorial/t_fe.html):

```

# 1. Choose a dataset.
from autogl.datasets import build_dataset_from_name
data = build_dataset_from_name('cora')

# 2. Compose a feature engineering pipeline
from autogl.module.feature import BaseFeature,AutoFeatureEngineer
from autogl.module.feature.generators import GeEigen
from autogl.module.feature.selectors import SeGBDT
from autogl.module.feature.graph import SgNetLSD
# you may compose feature engineering bases through BaseFeature.compose
fe = BaseFeature.compose([
GeEigen(size=32) ,
SeGBDT(fixlen=100),
SgNetLSD()
])
# or just through '&' operator
fe = fe & AutoFeatureEngineer(fixlen=200,max_epoch=3)

# 3. Fit and transform the data
fe.fit(data)
data1=fe.transform(data,inplace=False)
```

I always get 

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.9/site-packages/autogl-0.2.0rc0-py3.9.egg/autogl/module/feature/base.py", line 113, in fit
    dataset = self._rebuild(dataset, _dataset)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.9/site-packages/autogl-0.2.0rc0-py3.9.egg/autogl/module/feature/base.py", line 55, in _rebuild
    dataset.slices.update(slices)
AttributeError: 'NoneType' object has no attribute 'update'

**To Reproduce**

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 20.04 LTS
 - python version: 3.9.7
 - autogl version: 0.2.0-pre

 - pip list: conda list
# packages in environment at /home/ruhkopf/miniconda3/envs/AutoGL:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
astor                     0.8.1                    pypi_0    pypi
bayesian-optimization     1.2.0                    pypi_0    pypi
blas                      1.0                         mkl  
bottleneck                1.3.2            py39hdd57654_1  
brotlipy                  0.7.0           py39h27cfd23_1003  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py39h06a4308_0  
cffi                      1.14.5           py39h261ae71_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
chocolate                 0.0.2                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
configparser              5.1.0                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
cryptography              35.0.0           py39hd23ed53_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0                   pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
filelock                  3.3.2                    pypi_0    pypi
fonttools                 4.28.1                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.24                   pypi_0    pypi
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
hyperopt                  0.1.2                    pypi_0    pypi
idna                      3.2                pyhd3eb1b0_0  
intel-openmp              2021.4.0          h06a4308_3561  
isodate                   0.6.0                    pypi_0    pypi
jinja2                    3.0.2              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
json-tricks               3.15.5                   pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libuv                     1.40.0               h7b6447c_0  
lightgbm                  3.3.1                    pypi_0    pypi
littleutils               0.2.2                    pypi_0    pypi
markupsafe                2.0.1            py39h27cfd23_0  
matplotlib                3.5.0rc1                 pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
ncurses                   6.3                  h7f8727e_2  
netlsd                    1.0.2                    pypi_0    pypi
networkx                  2.6.3              pyhd3eb1b0_0  
nni                       2.5                      pypi_0    pypi
numexpr                   2.7.3            py39h22e1b3c_1  
numpy                     1.21.2           py39h20f2e39_0  
numpy-base                1.21.2           py39h79a1101_0  
ogb                       1.3.2                    pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
outdated                  0.2.1                    pypi_0    pypi
packaging                 21.2                     pypi_0    pypi
pandas                    1.3.4            py39h8c16a72_0  
pathtools                 0.1.2                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.4           py39h06a4308_0  
prettytable               2.4.0                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
protobuf                  3.19.1                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyg                       2.0.2           py39_torch_1.10.0_cu113    pyg
pymongo                   3.12.1                   pypi_0    pypi
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-louvain            0.15               pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pythonwebhdfs             0.2.3                    pypi_0    pypi
pytorch                   1.10.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-cluster           1.5.9           py39_torch_1.10.0_cu113    pyg
pytorch-mutex             1.0                        cuda    pytorch
pytorch-scatter           2.0.9           py39_torch_1.10.0_cu113    pyg
pytorch-sparse            0.6.12          py39_torch_1.10.0_cu113    pyg
pytorch-spline-conv       1.2.1           py39_torch_1.10.0_cu113    pyg
pytz                      2021.3             pyhd3eb1b0_0  
pyyaml                    6.0              py39h7f8727e_1  
rdflib                    6.0.2                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd3eb1b0_0  
responses                 0.15.0                   pypi_0    pypi
schema                    0.7.4                    pypi_0    pypi
scikit-learn              1.0.1            py39h51133e4_0  
scipy                     1.7.1            py39h292c36d_2  
sentry-sdk                1.4.3                    pypi_0    pypi
setuptools                58.0.4           py39h06a4308_0  
setuptools-scm            6.3.2                    pypi_0    pypi
shortuuid                 1.0.8                    pypi_0    pypi
simplejson                3.17.5                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0  
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
subprocess32              3.5.4                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.11               h1ccaba5_0  
tomli                     1.2.2                    pypi_0    pypi
tqdm                      4.62.3             pyhd3eb1b0_1  
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.7             pyhd3eb1b0_0  
wandb                     0.12.6                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
websockets                10.0                     pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.2.5                h7b6447c_0  
yaspin                    2.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  

pip list
Package               Version
--------------------- ---------
astor                 0.8.1
autogl                0.2.0rc0
bayesian-optimization 1.2.0
Bottleneck            1.3.2
brotlipy              0.7.0
certifi               2021.10.8
cffi                  1.14.5
charset-normalizer    2.0.4
chocolate             0.0.2
click                 8.0.3
cloudpickle           2.0.0
colorama              0.4.4
configparser          5.1.0
contextlib2           21.6.0
cryptography          35.0.0
cycler                0.11.0
dill                  0.3.4
docker-pycreds        0.4.0
filelock              3.3.2
fonttools             4.28.1
future                0.18.2
gitdb                 4.0.9
GitPython             3.1.24
googledrivedownloader 0.4
hyperopt              0.1.2
idna                  3.2
isodate               0.6.0
Jinja2                3.0.2
joblib                1.1.0
json-tricks           3.15.5
kiwisolver            1.3.2
lightgbm              3.3.1
littleutils           0.2.2
MarkupSafe            2.0.1
matplotlib            3.5.0rc1
mkl-fft               1.3.1
mkl-random            1.2.2
mkl-service           2.4.0
NetLSD                1.0.2
networkx              2.6.3
nni                   2.5
numexpr               2.7.3
numpy                 1.21.2
ogb                   1.3.2
outdated              0.2.1
packaging             21.2
pandas                1.3.4
pathtools             0.1.2
Pillow                8.4.0
pip                   21.2.4
prettytable           2.4.0
promise               2.3
protobuf              3.19.1
psutil                5.8.0
pycparser             2.21
pymongo               3.12.1
pyOpenSSL             21.0.0
pyparsing             2.4.7
PySocks               1.7.1
python-dateutil       2.8.2
python-louvain        0.15
PythonWebHDFS         0.2.3
pytz                  2021.3
PyYAML                6.0
rdflib                6.0.2
requests              2.26.0
responses             0.15.0
schema                0.7.4
scikit-learn          1.0.1
scipy                 1.7.1
sentry-sdk            1.4.3
setuptools            58.0.4
setuptools-scm        6.3.2
shortuuid             1.0.8
simplejson            3.17.5
six                   1.16.0
smmap                 5.0.0
subprocess32          3.5.4
tabulate              0.8.9
termcolor             1.1.0
threadpoolctl         2.2.0
tomli                 1.2.2
torch                 1.10.0
torch-cluster         1.5.9
torch-geometric       2.0.2
torch-scatter         2.0.9
torch-sparse          0.6.12
torch-spline-conv     1.2.1
tqdm                  4.62.3
typing-extensions     3.10.0.2
urllib3               1.26.7
wandb                 0.12.6
wcwidth               0.2.5
websockets            10.0
wheel                 0.37.0
yacs                  0.1.6
yaspin                2.1.0

**Comment by Frozenmad** [comment]
Thanks for your information about error report! Zeyang, can you help check the issue @wondergo2017 ?

**Comment by timruhkopf** [comment]
Hey Guys, 
thank you for your quick answers. I just tried out the following:
I scraped my env & created a new one with the downgraded minimal requirement of python 3.6,

and tried installing using:
pip3 install torch==1.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
pip3 install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric==1.7 -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
pip3 install autogl

but it seems the torch-geometric install has some issues:
>>> torch.__version__
'1.10.0+cu113'
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.6/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.data
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 6, in <module>
    from .dataloader import DataLoader, DataListLoader, DenseDataLoader
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.6/site-packages/torch_geometric/data/dataloader.py", line 5, in <module>
    from torch._six import container_abcs, string_classes, int_classes
ImportError: cannot import name 'container_abcs'

pip3 list
Package                           Version
--------------------------------- ------------
ase                               3.22.0
astor                             0.8.1
autogl                            0.2.0rc0
backports.entry-points-selectable 1.1.1
bayesian-optimization             1.2.0
cached-property                   1.5.2
certifi                           2020.12.5
charset-normalizer                2.0.7
chocolate                         0.0.2
cloudpickle                       2.0.0
colorama                          0.4.4
contextlib2                       21.6.0
cycler                            0.11.0
dataclasses                       0.8
decorator                         4.4.2
dill                              0.3.4
distlib                           0.3.3
filelock                          3.3.2
future                            0.18.2
googledrivedownloader             0.4
h5py                              3.1.0
hyperopt                          0.1.2
idna                              3.3
importlib-metadata                4.8.2
importlib-resources               5.4.0
isodate                           0.6.0
Jinja2                            3.0.3
joblib                            1.1.0
json-tricks                       3.15.5
kiwisolver                        1.3.1
lightgbm                          3.3.1
littleutils                       0.2.2
llvmlite                          0.36.0
MarkupSafe                        2.0.1
matplotlib                        3.3.4
NetLSD                            1.0.2
networkx                          2.5.1
nni                               2.5
numba                             0.53.1
numpy                             1.19.5
ogb                               1.3.2
outdated                          0.2.1
pandas                            1.1.5
Pillow                            8.4.0
pip                               21.3.1
pipenv                            2021.5.29
platformdirs                      2.4.0
prettytable                       2.4.0
psutil                            5.8.0
pymongo                           3.12.1
pyparsing                         3.0.6
python-dateutil                   2.8.2
python-louvain                    0.15
PythonWebHDFS                     0.2.3
pytz                              2021.3
PyYAML                            6.0
rdflib                            5.0.0
requests                          2.26.0
responses                         0.15.0
schema                            0.7.4
scikit-learn                      0.24.2
scipy                             1.5.4
setuptools                        58.0.4
simplejson                        3.17.5
six                               1.16.0
tabulate                          0.8.9
threadpoolctl                     3.0.0
torch                             1.10.0+cu113
torch-cluster                     1.5.9
torch-geometric                   1.7.0
torch-scatter                     2.0.9
torch-sparse                      0.6.12
torch-spline-conv                 1.2.1
tqdm                              4.62.3
typing_extensions                 4.0.0
urllib3                           1.26.7
virtualenv                        20.10.0
virtualenv-clone                  0.5.6
wcwidth                           0.2.5
websockets                        9.1
wheel                             0.37.0
zipp                              3.6.0

Thank you for your help!

**Comment by Frozenmad** [comment]
Maybe the CUDA version and PyTorch version is too high for torch_geometric lower than 2.0. You can try installing them follow [this url](https://pytorch-geometric.readthedocs.io/en/1.7.1/notes/installation.html).

For example, try:
```
pip install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch_geometric==1.7.1 -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
pip install autogl
```

Hope the cmd above can help you

**Comment by timruhkopf** [comment]
Thank you very much in particular for your fast responses! All of the installations & imports work fine now.
However, upon executing :

```
from autogl.datasets import build_dataset_from_name
cora_dataset = build_dataset_from_name('cora')
```

I still run into issues: 
```

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/autogl/datasets/__init__.py", line 126, in build_dataset_from_name
    dataset = DATASET_DICT[dataset_name](path)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/autogl/datasets/pyg.py", line 88, in __init__
    Planetoid(path, dataset)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch_geometric/datasets/planetoid.py", line 59, in __init__
    self.data, self.slices = torch.load(self.processed_paths[0])
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'torch_geometric.data.storage'

```

Further more trying out some of the examples (e.g. examples/graph_classification.py) fail in the argparse, as the argument --mode=server is unrecognized:
```
import sys
sys.path.append("../")
import random
import torch
import numpy as np
from autogl.datasets import build_dataset_from_name, utils
from autogl.solver import AutoGraphClassifier
from autogl.module import Acc
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
if __name__ == "__main__":
    parser = ArgumentParser(
        "auto graph classification", formatter_class=ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        "--dataset",
        default="mutag",
        type=str,
        help="graph classification dataset",
        choices=["mutag", "imdb-b", "imdb-m", "proteins", "collab"],
    )
    parser.add_argument(
        "--configs", default="../configs/graphclf_full.yml", help="config files"
    )
    parser.add_argument("--device", type=int, default=0, help="device to run on")
    parser.add_argument("--seed", type=int, default=0, help="random seed")
args = parser.parse_args()
usage: auto graph classification [-h]
                                 [--dataset {mutag,imdb-b,imdb-m,proteins,collab}]
                                 [--configs CONFIGS] [--device DEVICE]
                                 [--seed SEED]
auto graph classification: error: unrecognized arguments: --mode=server
Process finished with exit code 2
```

**Comment by Frozenmad** [comment]
For the first error, it seems that your torch_geometric version is still above 2.0. Can you check the version of torch_geometric?
``` python
import torch_goemetric
print(torch_geometric.__version__)
```
If it is above 2.0, you can downgrade it by
```
pip install -U torch_geometric==1.7.1
```

For the second error, the --mode=server argument seems from the Pycharm you are using. I'm not familar with PyCharm, can check whether open a terminal and run the file through cmd help?

**Comment by timruhkopf** [comment]
for the first error: 
i checked again and i have the version 1.7.1

```>>> import torch_geometric
>>> torch_geometric.__version__
'1.7.1'
```

As for the second error; running it from cmd on the remote server with no additional arguments (and annotated a print on both version and used device), amounts to the following:

```
(AutoGL) ruhkopf@ulysses ~/PycharmProjects/AutoGL/examples $ python3 graph_classification.py
torch geometric version: 1.7.1, 
 running on device: NVIDIA GeForce RTX 3090
Traceback (most recent call last):
  File "graph_classification.py", line 54, in <module>
    dataset = build_dataset_from_name(args.dataset)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/autogl/datasets/__init__.py", line 126, in build_dataset_from_name
    dataset = DATASET_DICT[dataset_name](path)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/autogl/datasets/pyg.py", line 166, in __init__
    TUDataset(path, name=dataset)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch_geometric/datasets/tu_dataset.py", line 70, in __init__
    self.data, self.slices = torch.load(self.processed_paths[0])
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/ruhkopf/miniconda3/envs/AutoGL/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'torch_geometric.data.storage'
```

**Comment by Frozenmad** [comment]
Sorry for the inconvenient, we will have a check recently! Through the error code snippet, I saw that it went wrong when we were trying to read dataset from torch_geometric. Seems the torch_geometric lib you installed still has some issues. Can you help check whether the following code works for you?
``` python
from torch_geometric.datasets import Planetoid
dataset = Planetoid('data', 'Cora')
```

@SwiftieH @CoreLeader Can you guys help identify the error? Seems something went wrong about dataset under the dependencies given above.

**Comment by timruhkopf** [comment]
I am glad that you guys help me and are so responsive! I am actually very curious about you package and consider extending it to my use-case. 

For your question:
```python 
from torch_geometric.datasets import Planetoid
dataset = Planetoid('data', 'Cora')

```
```
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.tx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.allx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.y
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.ty
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.ally
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.graph
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.test.index
Processing...
Done!

```

the download worked just fine.

**Comment by Frozenmad** [comment]
Thanks for your interests! I think I know the error... It seems that the dataset you downloaded when using pyg 2.0 is blocking pyg 1.7 from working. You can try deleting the `~/.cache-autogl` folder and running our code again :)

**Comment by timruhkopf** [comment]
Thank you very much that did the trick!
