### ISSUE TITLE
[BUG] License

### ISSUE THREAD

**Issue by timruhkopf** [THUMNLab/AutoGL#61]
Hey Guys, 
I am still intrigued by your package and strongly consider using it.
There is unfortunately a potentially boring hinderance: 
You need to specify the copyright in the License:

>  Copyright [yyyy] [name of copyright owner]

**Comment by Frozenmad** [comment]
Thanks for pointing out! We will fix this quickly

**Comment by Frozenmad** [comment]
The LICENSE should be valid now. Thanks again for pointing out this problem!
