### ISSUE TITLE
Wrong returned type of autogl.datasets.utils.conversion.general_static_graphs_to_pyg_dataset

### ISSUE THREAD

**Issue by Frozenmad** [THUMNLab/AutoGL#68]
The returned value should be an instance of `torch_geometric.data.InMemoryDataset`.
Current returned value is of type `autogl.data._dataset._dataset.InMemoryDataset`.
Please make it succeed the correct class. @CoreLeader

**Comment by CoreLeader** [comment]
Solved in #67
