### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by lijiachen8863** [THUMNLab/AutoGL#7]
I install AutoGL through pip.
Like this 'pip install auto-graph-learning -i https://pypi.org/simple'
But return shows an error 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.'
I want to know how to solve, thank you!

**Comment by Frozenmad** [comment]
Hi, could you please provide your environment, Windows or Linux, and your python lists (`pip list`)?

**Comment by Frozenmad** [comment]
Since no response is received for too long, we will close this issue for now. Feel free to re-open if you have further problems & updates.
